server:
  port: 8098

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/security
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format-sql: true

sp:
  jwt:
    secret: hello
    life-time: 30