server:
  port: 8098

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/security
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format-sql: true

auth:
  jwt:
    secret-sign: 2dc1bd9fb515d95b149f5f18e4704e8b
    token-life-time: 7200 # 2 hours
    token-refresh-time: 2592000 # 30 day
  token:
    secret-key: 1d6ee82de3af77e3d7074853357e8c03